name: "Make some comments"

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  deploy:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == ':rocket: deploy') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, ':rocket: deploy'))
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Write a comment
        id: comment
        uses: actions/github-script@v6
        with:
          script: |
            const c = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hi! This is PR ##' + context.issue.number
            })
            console.log(c.data)
            return c.data
            
      - name: Wait a bit
        run: sleep 20
      
      - name: Update comment
        uses: actions/github-script@v6
        env:
          COMMENT: ${{ steps.comment.outputs.result }}
        with:
          script: |
            const comment = JSON.parse(process.env.COMMENT)
            console.log("comment id" + comment.id, comment)
            github.rest.issues.updateComment({
              comment_id: comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'All done!'
            })
