name: "Make some comments"

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  deploy:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == ':rocket: deploy') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, ':rocket: deploy'))
    runs-on: ubuntu-latest
    steps:
      - name: Write a comment
        id: comment
        uses: actions/github-script@v6
        with:
          script: |

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hi! This is PR #' + context.issue.number
            })
      
      - name: Wait a bit
        run: sleep 60
      
      - name: Update comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.updateComment({
              comment_id: ${{ steps.comment.id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'All done!'
            })
